/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthTokenPost200Response,
  AuthTokenPostRequest,
} from '../models';
import {
    AuthTokenPost200ResponseFromJSON,
    AuthTokenPost200ResponseToJSON,
    AuthTokenPostRequestFromJSON,
    AuthTokenPostRequestToJSON,
} from '../models';

export interface AuthTokenPostOperationRequest {
    authTokenPostRequest?: AuthTokenPostRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async authTokenPostRaw(requestParameters: AuthTokenPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthTokenPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthTokenPostRequestToJSON(requestParameters.authTokenPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokenPost200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authTokenPost(requestParameters: AuthTokenPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthTokenPost200Response> {
        const response = await this.authTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
