/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokenPostRequest
 */
export interface AuthTokenPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthTokenPostRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokenPostRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the AuthTokenPostRequest interface.
 */
export function instanceOfAuthTokenPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthTokenPostRequestFromJSON(json: any): AuthTokenPostRequest {
    return AuthTokenPostRequestFromJSONTyped(json, false);
}

export function AuthTokenPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokenPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function AuthTokenPostRequestToJSON(value?: AuthTokenPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'email': value.email,
    };
}

