/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokenPost200Response
 */
export interface AuthTokenPost200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthTokenPost200Response
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokenPost200Response
     */
    expiresIn?: string;
}

/**
 * Check if a given object implements the AuthTokenPost200Response interface.
 */
export function instanceOfAuthTokenPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthTokenPost200ResponseFromJSON(json: any): AuthTokenPost200Response {
    return AuthTokenPost200ResponseFromJSONTyped(json, false);
}

export function AuthTokenPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokenPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'expiresIn': !exists(json, 'expiresIn') ? undefined : json['expiresIn'],
    };
}

export function AuthTokenPost200ResponseToJSON(value?: AuthTokenPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'expiresIn': value.expiresIn,
    };
}

