/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganization
 */
export interface CreateOrganization {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganization
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganization
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateOrganization interface.
 */
export function instanceOfCreateOrganization(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateOrganizationFromJSON(json: any): CreateOrganization {
    return CreateOrganizationFromJSONTyped(json, false);
}

export function CreateOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CreateOrganizationToJSON(value?: CreateOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

