/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganizationsIdentifierGet404ResponseError } from './OrganizationsIdentifierGet404ResponseError';
import {
    OrganizationsIdentifierGet404ResponseErrorFromJSON,
    OrganizationsIdentifierGet404ResponseErrorFromJSONTyped,
    OrganizationsIdentifierGet404ResponseErrorToJSON,
} from './OrganizationsIdentifierGet404ResponseError';

/**
 * 
 * @export
 * @interface EmailAlreadyInUseError
 */
export interface EmailAlreadyInUseError {
    /**
     * 
     * @type {OrganizationsIdentifierGet404ResponseError}
     * @memberof EmailAlreadyInUseError
     */
    error?: OrganizationsIdentifierGet404ResponseError;
}

/**
 * Check if a given object implements the EmailAlreadyInUseError interface.
 */
export function instanceOfEmailAlreadyInUseError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailAlreadyInUseErrorFromJSON(json: any): EmailAlreadyInUseError {
    return EmailAlreadyInUseErrorFromJSONTyped(json, false);
}

export function EmailAlreadyInUseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAlreadyInUseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : OrganizationsIdentifierGet404ResponseErrorFromJSON(json['error']),
    };
}

export function EmailAlreadyInUseErrorToJSON(value?: EmailAlreadyInUseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': OrganizationsIdentifierGet404ResponseErrorToJSON(value.error),
    };
}

