/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HealthGet200ResponseDependenciesInner } from './HealthGet200ResponseDependenciesInner';
import {
    HealthGet200ResponseDependenciesInnerFromJSON,
    HealthGet200ResponseDependenciesInnerFromJSONTyped,
    HealthGet200ResponseDependenciesInnerToJSON,
} from './HealthGet200ResponseDependenciesInner';

/**
 * 
 * @export
 * @interface HealthGet200Response
 */
export interface HealthGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof HealthGet200Response
     */
    healthy?: boolean;
    /**
     * 
     * @type {Array<HealthGet200ResponseDependenciesInner>}
     * @memberof HealthGet200Response
     */
    dependencies?: Array<HealthGet200ResponseDependenciesInner>;
}

/**
 * Check if a given object implements the HealthGet200Response interface.
 */
export function instanceOfHealthGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthGet200ResponseFromJSON(json: any): HealthGet200Response {
    return HealthGet200ResponseFromJSONTyped(json, false);
}

export function HealthGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'healthy': !exists(json, 'healthy') ? undefined : json['healthy'],
        'dependencies': !exists(json, 'dependencies') ? undefined : ((json['dependencies'] as Array<any>).map(HealthGet200ResponseDependenciesInnerFromJSON)),
    };
}

export function HealthGet200ResponseToJSON(value?: HealthGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'healthy': value.healthy,
        'dependencies': value.dependencies === undefined ? undefined : ((value.dependencies as Array<any>).map(HealthGet200ResponseDependenciesInnerToJSON)),
    };
}

