/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganizationsGet200ResponseOrganizationsInner } from './OrganizationsGet200ResponseOrganizationsInner';
import {
    OrganizationsGet200ResponseOrganizationsInnerFromJSON,
    OrganizationsGet200ResponseOrganizationsInnerFromJSONTyped,
    OrganizationsGet200ResponseOrganizationsInnerToJSON,
} from './OrganizationsGet200ResponseOrganizationsInner';

/**
 * 
 * @export
 * @interface OrganizationsGet200Response
 */
export interface OrganizationsGet200Response {
    /**
     * 
     * @type {Array<OrganizationsGet200ResponseOrganizationsInner>}
     * @memberof OrganizationsGet200Response
     */
    organizations?: Array<OrganizationsGet200ResponseOrganizationsInner>;
}

/**
 * Check if a given object implements the OrganizationsGet200Response interface.
 */
export function instanceOfOrganizationsGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationsGet200ResponseFromJSON(json: any): OrganizationsGet200Response {
    return OrganizationsGet200ResponseFromJSONTyped(json, false);
}

export function OrganizationsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organizations': !exists(json, 'organizations') ? undefined : ((json['organizations'] as Array<any>).map(OrganizationsGet200ResponseOrganizationsInnerFromJSON)),
    };
}

export function OrganizationsGet200ResponseToJSON(value?: OrganizationsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organizations': value.organizations === undefined ? undefined : ((value.organizations as Array<any>).map(OrganizationsGet200ResponseOrganizationsInnerToJSON)),
    };
}

