/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationsIdentifierPatchRequest
 */
export interface OrganizationsIdentifierPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationsIdentifierPatchRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationsIdentifierPatchRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the OrganizationsIdentifierPatchRequest interface.
 */
export function instanceOfOrganizationsIdentifierPatchRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationsIdentifierPatchRequestFromJSON(json: any): OrganizationsIdentifierPatchRequest {
    return OrganizationsIdentifierPatchRequestFromJSONTyped(json, false);
}

export function OrganizationsIdentifierPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsIdentifierPatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function OrganizationsIdentifierPatchRequestToJSON(value?: OrganizationsIdentifierPatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

