/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationsIdentifierGet404ResponseError
 */
export interface OrganizationsIdentifierGet404ResponseError {
    /**
     * 
     * @type {string}
     * @memberof OrganizationsIdentifierGet404ResponseError
     */
    msg?: string;
}

/**
 * Check if a given object implements the OrganizationsIdentifierGet404ResponseError interface.
 */
export function instanceOfOrganizationsIdentifierGet404ResponseError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationsIdentifierGet404ResponseErrorFromJSON(json: any): OrganizationsIdentifierGet404ResponseError {
    return OrganizationsIdentifierGet404ResponseErrorFromJSONTyped(json, false);
}

export function OrganizationsIdentifierGet404ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsIdentifierGet404ResponseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function OrganizationsIdentifierGet404ResponseErrorToJSON(value?: OrganizationsIdentifierGet404ResponseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
    };
}

