/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationsGet200ResponseOrganizationsInner
 */
export interface OrganizationsGet200ResponseOrganizationsInner {
    /**
     * 
     * @type {string}
     * @memberof OrganizationsGet200ResponseOrganizationsInner
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationsGet200ResponseOrganizationsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationsGet200ResponseOrganizationsInner
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationsGet200ResponseOrganizationsInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationsGet200ResponseOrganizationsInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the OrganizationsGet200ResponseOrganizationsInner interface.
 */
export function instanceOfOrganizationsGet200ResponseOrganizationsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function OrganizationsGet200ResponseOrganizationsInnerFromJSON(json: any): OrganizationsGet200ResponseOrganizationsInner {
    return OrganizationsGet200ResponseOrganizationsInnerFromJSONTyped(json, false);
}

export function OrganizationsGet200ResponseOrganizationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsGet200ResponseOrganizationsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function OrganizationsGet200ResponseOrganizationsInnerToJSON(value?: OrganizationsGet200ResponseOrganizationsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'name': value.name,
        'description': value.description,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}

