/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationsPost201Response
 */
export interface OrganizationsPost201Response {
    /**
     * 
     * @type {string}
     * @memberof OrganizationsPost201Response
     */
    identifier?: string;
}

/**
 * Check if a given object implements the OrganizationsPost201Response interface.
 */
export function instanceOfOrganizationsPost201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationsPost201ResponseFromJSON(json: any): OrganizationsPost201Response {
    return OrganizationsPost201ResponseFromJSONTyped(json, false);
}

export function OrganizationsPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsPost201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
    };
}

export function OrganizationsPost201ResponseToJSON(value?: OrganizationsPost201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
    };
}

