/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganizationsGet200ResponseOrganizationsInner } from './OrganizationsGet200ResponseOrganizationsInner';
import {
    OrganizationsGet200ResponseOrganizationsInnerFromJSON,
    OrganizationsGet200ResponseOrganizationsInnerFromJSONTyped,
    OrganizationsGet200ResponseOrganizationsInnerToJSON,
} from './OrganizationsGet200ResponseOrganizationsInner';

/**
 * 
 * @export
 * @interface OrganizationsIdentifierGet200Response
 */
export interface OrganizationsIdentifierGet200Response {
    /**
     * 
     * @type {OrganizationsGet200ResponseOrganizationsInner}
     * @memberof OrganizationsIdentifierGet200Response
     */
    organization?: OrganizationsGet200ResponseOrganizationsInner;
}

/**
 * Check if a given object implements the OrganizationsIdentifierGet200Response interface.
 */
export function instanceOfOrganizationsIdentifierGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationsIdentifierGet200ResponseFromJSON(json: any): OrganizationsIdentifierGet200Response {
    return OrganizationsIdentifierGet200ResponseFromJSONTyped(json, false);
}

export function OrganizationsIdentifierGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationsIdentifierGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organization': !exists(json, 'organization') ? undefined : OrganizationsGet200ResponseOrganizationsInnerFromJSON(json['organization']),
    };
}

export function OrganizationsIdentifierGet200ResponseToJSON(value?: OrganizationsIdentifierGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organization': OrganizationsGet200ResponseOrganizationsInnerToJSON(value.organization),
    };
}

