/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchUser
 */
export interface PatchUser {
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    lastName?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchUser
     */
    permissionFlags?: number;
}

/**
 * Check if a given object implements the PatchUser interface.
 */
export function instanceOfPatchUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchUserFromJSON(json: any): PatchUser {
    return PatchUserFromJSONTyped(json, false);
}

export function PatchUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'permissionFlags': !exists(json, 'permissionFlags') ? undefined : json['permissionFlags'],
    };
}

export function PatchUserToJSON(value?: PatchUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'permissionFlags': value.permissionFlags,
    };
}

