/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersGet200ResponseUsersInner } from './UsersGet200ResponseUsersInner';
import {
    UsersGet200ResponseUsersInnerFromJSON,
    UsersGet200ResponseUsersInnerFromJSONTyped,
    UsersGet200ResponseUsersInnerToJSON,
} from './UsersGet200ResponseUsersInner';

/**
 * 
 * @export
 * @interface UsersGet200Response
 */
export interface UsersGet200Response {
    /**
     * 
     * @type {Array<UsersGet200ResponseUsersInner>}
     * @memberof UsersGet200Response
     */
    users?: Array<UsersGet200ResponseUsersInner>;
}

/**
 * Check if a given object implements the UsersGet200Response interface.
 */
export function instanceOfUsersGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersGet200ResponseFromJSON(json: any): UsersGet200Response {
    return UsersGet200ResponseFromJSONTyped(json, false);
}

export function UsersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': !exists(json, 'users') ? undefined : ((json['users'] as Array<any>).map(UsersGet200ResponseUsersInnerFromJSON)),
    };
}

export function UsersGet200ResponseToJSON(value?: UsersGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': value.users === undefined ? undefined : ((value.users as Array<any>).map(UsersGet200ResponseUsersInnerToJSON)),
    };
}

