/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersGet200ResponseUsersInner
 */
export interface UsersGet200ResponseUsersInner {
    /**
     * 
     * @type {string}
     * @memberof UsersGet200ResponseUsersInner
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet200ResponseUsersInner
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet200ResponseUsersInner
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet200ResponseUsersInner
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersGet200ResponseUsersInner
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof UsersGet200ResponseUsersInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersGet200ResponseUsersInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof UsersGet200ResponseUsersInner
     */
    permissionFlags: number;
}

/**
 * Check if a given object implements the UsersGet200ResponseUsersInner interface.
 */
export function instanceOfUsersGet200ResponseUsersInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "permissionFlags" in value;

    return isInstance;
}

export function UsersGet200ResponseUsersInnerFromJSON(json: any): UsersGet200ResponseUsersInner {
    return UsersGet200ResponseUsersInnerFromJSONTyped(json, false);
}

export function UsersGet200ResponseUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersGet200ResponseUsersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'email': json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'permissionFlags': json['permissionFlags'],
    };
}

export function UsersGet200ResponseUsersInnerToJSON(value?: UsersGet200ResponseUsersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'email': value.email,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'permissionFlags': value.permissionFlags,
    };
}

