/* tslint:disable */
/* eslint-disable */
/**
 * API Kulturdaten.Berlin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersGet200ResponseUsersInner } from './UsersGet200ResponseUsersInner';
import {
    UsersGet200ResponseUsersInnerFromJSON,
    UsersGet200ResponseUsersInnerFromJSONTyped,
    UsersGet200ResponseUsersInnerToJSON,
} from './UsersGet200ResponseUsersInner';

/**
 * 
 * @export
 * @interface UsersIdentifierGet200Response
 */
export interface UsersIdentifierGet200Response {
    /**
     * 
     * @type {UsersGet200ResponseUsersInner}
     * @memberof UsersIdentifierGet200Response
     */
    user?: UsersGet200ResponseUsersInner;
}

/**
 * Check if a given object implements the UsersIdentifierGet200Response interface.
 */
export function instanceOfUsersIdentifierGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersIdentifierGet200ResponseFromJSON(json: any): UsersIdentifierGet200Response {
    return UsersIdentifierGet200ResponseFromJSONTyped(json, false);
}

export function UsersIdentifierGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIdentifierGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UsersGet200ResponseUsersInnerFromJSON(json['user']),
    };
}

export function UsersIdentifierGet200ResponseToJSON(value?: UsersIdentifierGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UsersGet200ResponseUsersInnerToJSON(value.user),
    };
}

